### PR TITLE
updated comments on parser examples

### PR DESCRIPTION
**Pull request by haseth**
Updated comments on parser examples.

### CODE REVIEW

**Comment by haseth** [comment]
@robfig Is it good to go in?

**Comment by robfig** [comment]
Ah, thanks for finding that typo. Actually, can you change the declaration from subsParser to specParser? I'm not sure what "subs" could stand for, and specParser would be consistent with the first example in that comment. 

Thanks!

**Comment by haseth** [comment]
Updated to `specParser` to make it consistent. :)

**Comment by robfig** [comment]
Thanks!

**Pull request merged**
