### PR TITLE
Added key, ability to remove and tests

### PR DESCRIPTION
**Pull request by britzc**

### CODE REVIEW

**Comment by JalfResi** [comment]
When can we expect this PR to be merged into master? I'd really like to use this package but the inability to delete entries is a bit of a blocker!

**Comment by britzc** [comment]
At the moment there is a version under britzc/cron, but i would prefer to contribute to the robfig library and not another version.

Regards
Corneile Britz

**Comment by briandowns** [comment]
+1  I'm in the same boat as @JalfResi

**Comment by trungpham** [comment]
Any chance of merging this? Very desired feature.

**Comment by britzc** [comment]
Hi, welcome to use britzc/cron till this repo is updated.

Regards
Corneile

**Comment by robfig** [comment]
I believe these features in the v2 branch

import "gopkg.in/robfig/cron.v2"

I may try to merge that to master soon; I just hate making backwards incompatible changes though

**Comment by robfig** [comment]
(Reopen if not!)

**Pull request closed without merging**
