### PR TITLE
-Add feature:Remove() and AddOnceFunc() support once run job

### PR DESCRIPTION
**Pull request by wgliang**

### CODE REVIEW

**Comment by damdo** [comment]
@robfig Can this be merged?

**Comment by wgliang** [comment]
PTAL 
@robfig

**Comment by wgliang** [comment]
ack @robfig

**Comment by AMecea** [comment]
How much will take to merge this? @robfig ?

**Comment by yeaze** [comment]
This is the feature that I want, thank you @wgliang 
@robfig Can this be merged?

**Comment by duguying** [comment]
i've f**ked this repo here https://github.com/gogather/cron . it's support remove func, etc.

**Comment by jniedrauer** [comment]
@robfig is this repo no longer maintained?

**Comment by robfig** [comment]
It's true, I haven't had much free time in the past couple years due to marriage, kids, the usual excuses. However, last week I did start on v3 to support Go Modules address all outstanding issues, starting with a merge to get the fixes from master and new features from v2 branch.  I suspect I can complete it within the next month, by Mar 1, 2019. 

To answer the earlier question, I have no plans to merge this pull request. It has no description of the motivating use case or exactly what this is supposed to implement, no updates to documentation, not even updates to the godoc for funcs with changed signatures. What is the point of using a cron package to run a function once? It also contains an implementation of Remove which would conflict with the implementation in the v2 branch. If anyone would like to use this PR, that's what forks are for!

**Pull request closed without merging**
