### PR TITLE
add Wait() function to await job completion

### LINKED ISSUE #98: There is no way to wait for completion of started Jobs after calling Stop()
When calling `Stop()` there may still be be Jobs whose Goroutines have been created but were never scheduled. It is therefore impossible to wait for all Jobs to complete, because some may not yet be running, making it impossible to track them.

The right place for adding to a `sync.WaitGroup` would be in `Cron:run()` right before `go c.runWithRecovery(e.Job)`. You could then add a new `Cron:Wait()` function for waiting for jobs to finish after calling `Stop()`.

### PR DESCRIPTION
**Pull request by mrwonko**
fixes #98

### CODE REVIEW

**Comment by bgaifullin** [comment]
IMO: this functional out of scope crop. a client can wait all running jobs in its own side, for example by adding counter to each job.

**Comment by mrwonko** [comment]
But there is no guarantee that no new Job will be launched after you called Stop() - once you start a Goroutine with `go c.runWithRecovery(e.Job)` there is no guarantee it will actually be scheduled any time soon, it can sit around idly for an arbitrary time.

**Comment by bgaifullin** [comment]
You are right, but it also can be handled on client side. You can design your jobs for skipping run if system is going to shutdown.
IMO: it is better to avoid adding non fundamental functional which brings additional overhead.

**Comment by mrwonko** [comment]
Sure, it _can_ be added clientside, but it's a lot of hassle to get right:
```Go
	c := cron.New()
	var mu sync.Mutex
	var wg sync.WaitGroup
	stop := false
	c.AddFunc("* * * * * *", func() {
		mu.Lock()
		if stop {
			mu.Unlock()
			return
		}
		wg.Add(1)
		mu.Unlock()
		// ...
		wg.Done()
	})
	c.Start()
	// ...
	c.Stop()
	mu.Lock()
	stop = true
	mu.Unlock()
	wg.Wait()
```

Contrast that with
```Go
	c := cron.New()
	c.AddFunc("* * * * * *", func() {
		// ...
	})
	c.Start()
	// ...
	c.Stop()
	c.Wait()
```
and how simple the changes to cron required to support this are.

**Comment by se3000** [comment]
We need this too. Are there any blockers from getting this merged?

**Comment by robfig** [comment]
Sorry for the long silence. c.Stop() now returns a context that you can wait on to accomplish this use case.

**Pull request closed without merging**
