### PR TITLE
Support for 'H' as a randomization parameter

### PR DESCRIPTION
**Pull request by mhupman**
I think this will work fine, but not sure if it needs unit tests (or what the best way to test it would be).  It seems like the only thing worth testing is whether or not the range passed to `Intn()` gets incremented so it becomes inclusive - thoughts?

### CODE REVIEW

**Comment by robfig** [comment]
I think the way to test it would be to replace the "random" variable with a random source with a specified seed. Tests are worth it, IMO

**Comment by mhupman** [comment]
So, I did get pretty far down the testing path and ended up abandoning it when I ran into some issues:

- I can construct a `rand.Source` to ensure the same seed is used during tests, but the numbers returned by `rand.Intn()` would still be a pseudo-random.  I could hardcode tests assuming same stream comes back every time, but that seems brittle?
- In the end, if I controlled the random values, it seems like all I would be testing is that the range I'm passing to the Intn function is correct (accounting for half-open range, for example).

Anyway, I struggled with whether that was worth testing or how contrived it would be.  I got as far as mocking `rand.Intn()` and then validating that given a range `{0, 60}`, the rand function received `{0, 59}`.  That seemed pretty silly though, so I dropped it.

**Comment by robfig** [comment]
I'm quite sure that you are guaranteed that the pseudo-random sequence will not change given the same seed, across different runs of the program. e.g. http://play.golang.org/p/HICPQ5ay90

If you want to control the random numbers provided, declaring a 

```go
type rand interface { Int31() int32 } 
```
doesn't seem so bad either. 

I do think adding a new feature like this needs some sort of test coverage and documentation update

**Comment by robfig** [comment]
Any interest in continuing this PR?

**Comment by crazy-max** [comment]
@robfig @mhupman Maybe I can take over this PR?

**Comment by mhupman** [comment]
@crazy-max sounds good!

**Pull request closed without merging**
