### PR TITLE
Protecting start from double runs.

### PR DESCRIPTION
**Pull request by pascallouisperez**

### CODE REVIEW

**Comment by allonhadaya** [comment]
@pascallouisperez Out of curiosity, what's the idea behind changing `running` from `bool` to `*int32`. Are there no facilities for working atomically with bools? If so, do you know why? Thanks!

**Comment by shurcooL** [comment]
@allonhadaya, take a look at https://godoc.org/sync/atomic to see what's available.

**Comment by pascallouisperez** [comment]
There are no utilities to deal with atomic bools because the atomic package exposes lower-level functionality. For instance, atomic operations on 64bit memory locations are only supported by certain processors.

**Comment by allonhadaya** [comment]
@pascallouisperez Ah, that explains it! Thanks you.

**Comment by pascallouisperez** [comment]
@allonhadaya Will you merge this PR?

**Comment by pascallouisperez** [comment]
@robfig Or, is only Rob allowed to?

**Comment by allonhadaya** [comment]
@pascallouisperez Definitely @robfig or someone he would delegate to. I'm only superficially familiar with this codebase. Good luck!

**Comment by robfig** [comment]
Hi @pascallouisperez, 
Out of curiosity, was the issue that you ran into multiple calls to Start(), accidentally?
I think this implementation looks fine, except we should not be exporting A_TRUE/A_FALSE constants.  
Thanks!

**Comment by orian** [comment]
Just saying that preventing multiple execution of a job in time can be done through creating a Job wrapper:
https://github.com/orian/utils/blob/master/concurency/concurency.go

**Pull request closed without merging**
